#!/bin/bash

# TestFlight Upload Script
IPA_PATH="/Users/yuki/jitsuflow/build/ios/ipa/JitsuFlow.ipa"
APP_STORE_EMAIL="mail@yukihamada.jp"

echo "================================================"
echo "JitsuFlow TestFlight Upload Script"
echo "================================================"
echo ""
echo "IPAファイル: $IPA_PATH"
echo "App Store Connect Email: $APP_STORE_EMAIL"
echo ""
echo "以下の手順でアップロードを進めてください："
echo ""
echo "1. App-specific passwordを生成:"
echo "   - https://appleid.apple.com にログイン"
echo "   - 「サインインとセキュリティ」→「アプリ固有のパスワード」"
echo "   - 新しいパスワードを生成（例：'JitsuFlow TestFlight'）"
echo ""
echo "2. 生成されたパスワードをコピーして、以下のコマンドを実行:"
echo ""
echo "xcrun altool --upload-app \\"
echo "  -f \"$IPA_PATH\" \\"
echo "  -t ios \\"
echo "  -u \"$APP_STORE_EMAIL\" \\"
echo "  -p \"YOUR_APP_SPECIFIC_PASSWORD\""
echo ""
echo "または、Xcodeから直接アップロード:"
echo "open ios/Runner.xcworkspace"
echo "Product → Archive → Distribute App → App Store Connect"
echo ""
echo "================================================"