name = "jitsuflow-api-docs"
main = "worker.js"
compatibility_date = "2024-01-01"
site = { bucket = "./public" }

[env.production]
name = "jitsuflow-api-docs-prod"

[[env.production.routes]]
pattern = "docs.jitsuflow.app"
custom_domain = true